services:
  - type: web
    name: xastral-bot
    repo: https://github.com/Diegoson/whatsapp-bot.git
    branch: main
    env: docker
    dockerfilePath: /media/Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: SESSION_ID
        sync: false
      - key: OWNER_NUM
        sync: false
      - key: MODS
        sync: false
      - key: WORKTYPE
        sync: false
