services:
  - type: web
    name: xastral-bot
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: SESSION_ID
        sync: false
      - key: OWNER_NUM
        sync: false
      - key: MODS
        sync: false
      - key: WORKTYPE
        sync: false
